### ISSUE TITLE
Release 1.3.8

### ISSUE THREAD

**Issue by srid** [GNUSim8085/GNUSim8085#7]
Mainly because we now have a new canonical repo and site. Let's use Github Releases to upload the tarballs and binaries right here: https://github.com/blog/1547-release-your-software
- [x] master branch ready for tag-release
- [x] Get approval from @srid
  - [x] Update srid's email address
- [x] Tag and upload binaries to Github
- [x] Announce
  - [x] Debian packaging
  - [x] Fedora
  - [x] Archlinux AUR
- [x] Remove releases older than 1.3.7 from launchpad
- [x] Figure out a way to include the licenses of all the libraries in Windows installer. (#29)
- [x] Decide if we should completely switch to GTK3 by removing option to build with GTK2. (#28)
- [x] Use markdown for creating user guide. (#30)
- [x] Update screenshots included in the source

**Comment by srid** [comment]
Or 1.4.0?

**Comment by onkarshinde** [comment]
The releases section has created tarball from two tags available in repository. But I assume this is just an archive of the repository. I do not see an option to add the tarballs we have generated or the Windows installer files.

As for 1.3.8 vs 1.4.0:
I prefer 1.3.x for now. I am working on port to GTK3, which will be included as an optional in 1.3.8. Once we have perfected build with GTK3 we can release 1.4.0.

**Comment by srid** [comment]
> I do not see an option to add the tarballs we have generated or the Windows installer files.

1. Go to https://github.com/GNUSim8085/GNUSim8085/releases
2. Click a release, e.g.: 1.3.7
3. Click "Edit tag" (top right)
4. Below the large text box, "Attach files by dragging & dropping or selecting them."

**Comment by srid** [comment]
> I prefer 1.3.x for now. I am working on port to GTK3, which will be included as an optional in 1.3.8. Once we have perfected build with GTK3 we can release 1.4.0.

+1

**Comment by HappyAndHarmless** [comment]
> Remove releases older than 1.3.7 from launchpad

Any reason 1.3.7 was not removed from launchpad (especially as it is available in Github Releases)?

**Comment by onkarshinde** [comment]
> Any reason 1.3.7 was not removed from launchpad (especially as it is available in Github Releases)?

I am still trying to figure out if there is a way to check the download statistics for the release on Github. Once it is confirmed that users are downloading from Github, I will shut down the download section on launchpad.

**Comment by HappyAndHarmless** [comment]
Github provides an [API](https://help.github.com/articles/getting-the-download-count-for-your-releases/) for getting download count.

**Comment by onkarshinde** [comment]
> Github provides an API for getting download count (example).

Knew that already. :-)
I have embedded the download statistics in the page now. Let me know your comments.

**Comment by onkarshinde** [comment]
I have removed the downloads from launchpad and also announced the movement to GitHub.

**Comment by onkarshinde** [comment]
@srid 
We are almost ready to release 1.3.8. But I believe that we need to achieve following things before that.
1. Figure out a way to include the licenses of all the libraries in Windows installer.
2. Decide if we should completely switch to GTK3 by removing option to build with GTK2. This will remove a bunch of if/else in code and build scripts. I can track this under separate issue. We can then do some code refactoring in future versions for making better use of GTK3 APIs.
3. I had started writing a user manual in docbook which can be converted to HTML at build time. I never completed the manual even though the build process is in place. Now that I have discovered the concept of markdown, I think docbook is overkill for this. I can also log a separate issue for this.

Number 1 is must for 1.3.8. Let me know out of 2 and 3 which ones should I target for 1.3.8.

**Comment by srid** [comment]
Let's target 2

**Comment by srid** [comment]
This will be 1.4.0? Because of the GTK3 requirement.

**Comment by onkarshinde** [comment]
If you look at the screenshots in #23 you will see some weird problem with buttons expanding. If I manage to solve this problem then version will be 1.4.0, otherwise it will remain 1.3.8.

**Comment by onkarshinde** [comment]
I am done with all the code changes. I now need to setup chroot so that I can create Ubuntu packages.
Should I bump version to 1.4.0, tag and create a draft release?

**Comment by srid** [comment]
if its ready yea

**Comment by onkarshinde** [comment]
I messed up something in release. The source distribution I created does not build. :-1: 
I have reverted the website to point to old release, kept the new screenshots though. I will try to sort out mess and create a 1.4.1 build.

**Comment by onkarshinde** [comment]
Published release 1.4.1 now along with Windows installer and .deb for i386 and amd64. The download page on the site has been updated. Please test and let me know any comments.

**Comment by onkarshinde** [comment]
@srid @aanjhan I have sent the release notification to pkg-electronics-devel@alioth-lists.debian.net. Are there any other places you want to announce this?

**Comment by onkarshinde** [comment]
Sent notification to the Fedora package maintainer and Arch Linux AUR package maintainer. Let's see how it goes.

**Comment by onkarshinde** [comment]
No response from AUR maintainer yet. I have flagged the package as out-of-date.
Debian package is almost ready, expected to be uploaded to unstable when sponsor is back from vacation.

@aanjhan Do you know if we need to log a bug for Fedora to announce new versions?

**Comment by onkarshinde** [comment]
Logged a low priority bug on Fedora bug tracker.
https://bugzilla.redhat.com/show_bug.cgi?id=1618832

The package has entered Debian unstable as well as Ubuntu Cosmic (18.10).

As for AUR I have the PKGBUILD ready. But as per policy I have to wait at least two weeks from the date when package is marked as out of date before it is marked as orphaned and can be taken over.

**Comment by onkarshinde** [comment]
I have requested the AUR package to be orphaned so that I can take over the maintenance.

@srid, if there is nothing else to be done then I will close the issue.

**Comment by onkarshinde** [comment]
Closing this as nothing else is to be done.
